- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Enable webapp site
  file:
    src: /etc/nginx/sites-available/webapp.conf
    dest: /etc/nginx/sites-enabled/webapp.conf
    state: link
    force: yes

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

