- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure basic packages are installed
  apt:
    name:
      - python3
      - python3-venv
      - python3-pip
      - git
      - curl
      - build-essential
      - python3-psycopg2   # нужно для community.postgresql
    state: present

