- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Ensure DB user
  community.postgresql.postgresql_user:
    name: webapp
    password: secret_password_here
    state: present
    login_user: postgres
    login_password: your_postgres_root_password
    login_host: 127.0.0.1

- name: Ensure DB
  community.postgresql.postgresql_db:
    name: webapp_db
    owner: webapp
    state: present
    login_user: postgres
    login_password: your_postgres_root_password
    login_host: 127.0.0.1

