- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Ensure DB user
  become_user: postgres
  postgresql_user:
    name: webapp
    password: secret_password_here
    state: present

- name: Ensure DB
  become_user: postgres
  postgresql_db:
    name: webapp_db
    owner: webapp
    state: present

