name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # ------------------ Фронтенд ------------------
    - name: Build frontend
      run: |
        mkdir -p services/frontend/dist
        cp services/frontend/build/* services/frontend/dist/
    
    # ------------------ Установка Ansible ------------------
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible sshpass

    # ------------------ Развертывание через Ansible ------------------
    - name: Run Ansible Playbook
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/repo-root
          ansible-playbook -i inventory/hosts.ini playbooks/site.yml

