name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # ------------------ Checkout ------------------
    - name: Checkout repository
      uses: actions/checkout@v3

    # ------------------ Prepare frontend ------------------
    - name: Prepare frontend
      run: |
        echo "Frontend build already exists, copying..."
        ls -l services/frontend/build

    # ------------------ Install Ansible ------------------
    - name: Install Ansible and SSH tools
      run: |
        sudo apt update
        sudo apt install -y ansible sshpass rsync

    # ------------------ Deploy via Ansible ------------------
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/repo-root
          ansible-playbook -i inventory/hosts.ini playbooks/site.yml

