name: CI/CD — build & deploy


on:
push:
branches: [ main ]


jobs:
build-and-deploy:
runs-on: ubuntu-latest


steps:
- name: Checkout
uses: actions/checkout@v4


- name: Set up Node (for frontend build)
uses: actions/setup-node@v4
with:
node-version: '18'


- name: Install frontend deps & build
working-directory: ./services/frontend
run: |
npm ci
npm run build


- name: Prepare artifact to copy
run: |
rm -rf dist_frontend_build || true
mkdir -p dist_frontend_build
cp -r services/frontend/build/* dist_frontend_build/


- name: Set up Python & Ansible
uses: actions/setup-python@v4
with:
python-version: '3.11'


- name: Install Ansible and rsync
run: |
python -m pip install --upgrade pip
pip install ansible==8.9.0
sudo apt-get update && sudo apt-get install -y rsync


- name: Add SSH key
uses: webfactory/ssh-agent@v0.6.0
with:
ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


- name: Run Ansible playbook
env:
ANSIBLE_HOST_KEY_CHECKING: 'False'
run: |
ansible-playbook -i inventory/hosts.ini playbooks/site.yml --ssh-extra-args='-o StrictHostKeyChecking=no'
