name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # ------------------ Checkout ------------------
    - name: Checkout repository
      uses: actions/checkout@v3

    # ------------------ Prepare Frontend ------------------
    - name: Prepare frontend
      run: |
        echo "Copying pre-built frontend into dist folder..."
        mkdir -p services/frontend/dist
        cp -r services/frontend/build/* services/frontend/dist/

    # ------------------ Install Ansible ------------------
    - name: Install Ansible and SSH tools
      run: |
        sudo apt update
        sudo apt install -y ansible sshpass

    # ------------------ Run Ansible Playbook ------------------
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/repo-root
          ansible-playbook -i inventory/hosts.ini playbooks/site.yml

